### ISSUE TITLE
Cannot read properties of undefined (reading 'stop')

### ISSUE THREAD

**Issue by SykesJohn** [rungwiroon/BlazorGoogleMaps#153] opened 2021-09-28 17:08 UTC
Steps to reproduce:

1. Run the Markers demo in ServerSideDemo.
2. Add a marker.
3. Click on marker.
4. Observe console.

**Comment by valentasm1** [comment] 2021-09-28 17:40
Which page do you use?
This one mapMarker
Do you click first button "Add marker"?

**Comment by SykesJohn** [comment] 2021-09-28 17:44
Was that not in the steps to reproduce? I have seen it in more than one place, so it may be everywhere.

**Comment by valentasm1** [comment] 2021-09-28 17:50
Could not reproduce. Could you provide more info. Exact steps, screenshots, call stack from console.

**Comment by SykesJohn** [comment] 2021-09-28 17:58
1.  Run ServerSideDemo (Debug mode)
  2.  Click Markers in the menu.
  3.  Click Add marker button to get a marker on the map.
  4.  Click on the marker.
  5.  Browser console shows:
TypeError: Cannot read properties of undefined (reading 'stop')
at Object.invoke (objectManager.js:433)
at blazor.server.js:8
at new Promise (<anonymous>)
at e.beginInvokeJSFromDotNet (blazor.server.js:8)
at blazor.server.js:1
at Array.forEach (<anonymous>)
at e.invokeClientMethod (blazor.server.js:1)
at e.processIncomingData (blazor.server.js:1)
at e.connection.onreceive (blazor.server.js:1)
at WebSocket.i.onmessage (blazor.server.js:1)

If you tell me how to submit (push) my branch to the repository you can have my code (I have added some demos).

**Comment by valentasm1** [comment] 2021-09-28 18:05
Which browser?
For me windows chrome, opera and firefox works well. 
You could create public repository or fork current on from top right.

**Comment by SykesJohn** [comment] 2021-09-28 18:07
Chrome. I’ll try Edge.

**Comment by valentasm1** [comment] 2021-09-28 18:14
Really sorry, but i dont know how i could help you. Maybe you need to update solution

**Comment by SykesJohn** [comment] 2021-09-28 18:16
Thanks. I tried that wit no effect.
I get a 403 when trying to push my branch.

**Comment by valentasm1** [comment] 2021-09-28 18:18
You have two solutions: create publish repository or fork it.

**Comment by valentasm1** [comment] 2021-09-28 18:20
Or third option fork and then make Pull Request

**Comment by SykesJohn** [comment] 2021-09-28 19:31
Could not reproduce in version 1.1.8.

**Comment by SykesJohn** [comment] 2021-09-28 19:36
Seems to only happen with builds from Visual Studio 2022.

**Comment by valentasm1** [comment] 2021-09-28 20:43
Cha cha now we exchanged our views. There is issue with event propagating. Lets say Marker::Click 
I commented one part which it adds event to array, since it didnt made sense. Now it does.
So it add event to array and it should return id of event when it happens when it is MouseEvent, so when you do e.Stop(); it should find that event and trigger Stop. Problem that it returns god know what id and closure event is also god know what. 50 line in js

**Comment by valentasm1** [comment] 2021-09-28 21:14
Aha found more clues. 
So e.Stop should be first action since if it is second (After get label) the that id is disposed in 75 line in js. Looks like blozor issue or it just works this way. Closing

**Closed** 2021-09-28 21:14 UTC
