### ISSUE TITLE
New feature (Beta) Marker google.maps.CollisionBehavior

### ISSUE THREAD

**Issue by joe-shapiro-biz** [rungwiroon/BlazorGoogleMaps#127] opened 2021-07-16 21:17 UTC
I wonder if you would please implement collisionBehavior in markeroptions or setCollisionBehavior on Marker.  Thanks.

**Comment by valentasm1** [comment] 2021-07-17 06:20
Do you have examples?

**Comment by joe-shapiro-biz** [comment] 2021-07-17 10:25
https://jsfiddle.net/api/post/library/pure/

choose “optional and hides lower priority”
and zoom out the map until some of the markers would overlap.
Notice that some markers become hidden so that others are unobstructed.

I think all you need to do is add the collisionBehavior member to markerOptions.
If you want to take a step further, also implement get and set collision behavior on Marker.

Thank you for your consideration. And thanks for this package.

**Comment by valentasm1** [comment] 2021-07-17 11:03
Could you double check link. It says "That page doesn't exist."

**Comment by joe-shapiro-biz** [comment] 2021-07-17 14:33
Sorry, try this

https://developers.google.com/maps/documentation/javascript/examples/marker-collision-management#

**Comment by valentasm1** [comment] 2021-07-17 14:55
Aha. This looks doable.
I will try to do this in comming day, if you wont get update in week just ping me here.

**Comment by joe-shapiro-biz** [comment] 2021-07-17 18:21
thank you so much.

**Comment by valentasm1** [comment] 2021-07-17 19:34
https://github.com/rungwiroon/BlazorGoogleMaps/releases/tag/1.0.16
```
   var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
            {
                Position = mapCenter,
                Map = map1.InteropObject,
                Label = $"Test {markers.Count}",
                CollisionBehavior = CollisionBehavior.OPTIONAL_AND_HIDES_LOWER_PRIORITY
             
            });

```

**Comment by valentasm1** [comment] 2021-07-17 19:34
Let me know if it works :).

**Comment by joe-shapiro-biz** [comment] 2021-07-17 19:49
Thanks. Tell you Monday.
________________________________

**Comment by joe-shapiro-biz** [comment] 2021-07-19 14:44
on first try, seems to have no effect.


        static int z = 0;
        public async Task addPing(SxGpsPing ping)
        {


            var Position = new LatLngLiteral(ping.X, ping.Y);
            var tripCode = tripCodes[ping.AlternateTripId.Value];
            var color = colors[tripCode];

            var opts = new MarkerOptions()
            {
                Position = Position,
                CollisionBehavior = CollisionBehavior.OPTIONAL_AND_HIDES_LOWER_PRIORITY,
                ZIndex = z++,
                Map = _Map.InteropObject,
                Icon = pingIcon(color),
                Label = "\t" + ping.GpsTimeStamp.ToLocalTime().ToShortTimeString(),
                Title = "\t" + ping.GpsTimeStamp.ToLocalTime().ToShortTimeString() 

            };
            var mk = await Marker.CreateAsync(_Map.JsRuntime, opts);

            var p = new Ping();
            p.ping = ping;
            p.marker = mk;

            pings[tripCode].Add(p);
        }




![2021-07-19](https://user-images.githubusercontent.com/17418029/126178696-aef19abd-39fd-4157-a05b-73aed1a93496.png)

**Comment by joe-shapiro-biz** [comment] 2021-07-19 14:48
what does this mean:    **_Need to set v=beta to make it work_**

**Comment by valentasm1** [comment] 2021-07-19 17:17
It should be like 
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_GOES_HERE&v=beta"></script>

**Comment by joe-shapiro-biz** [comment] 2021-07-19 21:48
sorry, no luck.

**Comment by valentasm1** [comment] 2021-07-20 06:09
I really dont know. All looks like google in google example. I assume it could be some flag in managament console. 
You could clone code and run server side sample MapMarker (server side have almost all possible demos) and then check how is set in after this line
```
if (propertyValue !== null && typeof propertyValue === "string" && propertyValue.indexOf("google.maps.CollisionBehavior") == 0) {
```
and in this method
```
createObject
```
in objectManager.js
Maybe make very simple local html demo for this functionality and then compare how blazor google maps sets and what is missing.

**Comment by valentasm1** [comment] 2021-07-20 06:10
I could try to look more this or coming week, but if you reproduce functionality on small html demo then you could find fast.

**Comment by joe-shapiro-biz** [comment] 2021-07-20 15:21
Thank you. Please do not put in any extraordinary effort for now. I’ll see if I can minimize an example.
________________________________

**Comment by valentasm1** [comment] 2021-09-03 08:03
Any update?

**Comment by joe-shapiro-biz** [comment] 2021-09-03 12:05
I have not attempted to fix it myself, but I have verified that I am setting all the appropriate values, yet the desired behavior does not occur. I will clone the repository when I have time and dig deeper, but right now I am under time pressure on another project. Thank you so much for the follow up.

**Comment by joe-shapiro-biz** [comment] 2021-09-07 12:12
I cloned the repository.

I modified index.html adding v=beta

I modified objectManager, adding console logging on each object after creation

I modified the ClientsideDemoNet5 project, adding CollisionBehavior, zIndex and varying positions to AddMarker as below.

What I find is: the object are definitely getting created with the properties that I expected, but zooming in close to the markers does not hide any markers. This is puzzling because the google sample at https://developers.google.com/maps/documentation/javascript/examples/marker-collision-management works exactly as I would expect.

So, in summary, I am baffled.

---- start code---

    static int z = 0;
    static Random rnd = new Random();

    private async Task AddMarker()
    {


        var newPosition = new LatLngLiteral(-75 + rnd.NextDouble() / 100, 40 + rnd.NextDouble() / 100 );
        await map1.InteropObject.SetCenter(newPosition);


        var marker = await Marker.CreateAsync(map1.JsRuntime, markers.Count() % 2 == 0 ?
            new MarkerOptions()
            {
                Position = newPosition,
                CollisionBehavior = CollisionBehavior.OPTIONAL_AND_HIDES_LOWER_PRIORITY,
                ZIndex = z++,
                Map = map1.InteropObject,
                Label = new MarkerLabel { Text = $"Test {markers.Count()}", FontWeight = "bold" },
                Icon = new Icon()
                {
                    Url = "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png"
                }
            } :
            new MarkerOptions()
            {
                Position = newPosition,
                CollisionBehavior = CollisionBehavior.OPTIONAL_AND_HIDES_LOWER_PRIORITY,
                ZIndex = z++,
                Map = map1.InteropObject,
                Label = $"Test {markers.Count()}",
                Icon = new Icon()
                {
                    Url = "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png"
                }
                //Icon = "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png"
            });

--- end code ----

**Comment by valentasm1** [comment] 2021-09-07 12:22
At least i could agree we both in same situation. Where it looks like it should work but it dont.
Ok i will check one more time too.

**Comment by joe-shapiro-biz** [comment] 2021-09-07 12:58
There are no settings in the google cloud console to enable v=beta.
I do notice that their sample uses a map Id and “ours” doesn’t.
Unlikely that this has any effect but I will try that.
BTW your mapOptions doesn’t include a MapId member.

**Comment by joe-shapiro-biz** [comment] 2021-09-07 13:15
So, it does seem to work if you provide a MapId.  Crazy.

**Comment by joe-shapiro-biz** [comment] 2021-09-07 13:16
Would you please add MapId to MapOptions?

**Comment by joe-shapiro-biz** [comment] 2021-09-07 13:41
also, it seem you have to supply an initial center in the map options.

**Comment by joe-shapiro-biz** [comment] 2021-09-07 14:00
and, maybe the map has to be vector style.

**Comment by valentasm1** [comment] 2021-09-07 14:29
For me providing MapId, v=beta was enough. It was working in server side demo
I dont understand why map id it is so important
https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.mapId

**Comment by valentasm1** [comment] 2021-09-07 14:36
Ahaaa it works when i provide mapid from google example "3a3b33f0edd6ed2a", but dont when i generate random.
So it should be related to google Maps Management page and your map api. 
I am leaving it for you to find out.

**Comment by joe-shapiro-biz** [comment] 2021-09-07 17:40
I’m satisfied. Thanks.

**Comment by valentasm1** [comment] 2021-09-07 17:42
Please when you find solution (regarding MapId) write it here. It will be usefull for someone else too.

**Comment by joe-shapiro-biz** [comment] 2021-09-07 17:46
I think I did already, but to summarize:
You need to define a map in your google cloud portal,
and it seems like it has to be a javascript/vector map.
Then you have to provide the mapId in the MapOptions object,
Which currently is not implemented in BlazorGoogleMaps but I derived a new class from that and gave it a string MapId.
Also, it seems to be important to give the MapOptions an initial position and zoom, but I’m not totally sure about that; doesn’t hurt in any case.

**Comment by valentasm1** [comment] 2021-09-07 18:02
MapId is implemented
https://github.com/rungwiroon/BlazorGoogleMaps/releases/tag/1.1.2
Thank you. Closing

**Comment by valentasm1** [comment] 2021-09-07 18:03
https://github.com/rungwiroon/BlazorGoogleMaps/commit/4b9b0a13647fdc51a14fd5f49cb4ec84fab90ce2

**Closed by valentasm1** 2021-09-07 18:02 UTC
