### ISSUE TITLE
AdvancedMarkerView.

### ISSUE THREAD

**Issue by vishalsmart** [rungwiroon/BlazorGoogleMaps#217] opened 2022-11-12 09:23 UTC
Hi, 

Can you please implement AdvancedMarkerView as well?

https://developers.google.com/maps/documentation/javascript/advanced-markers/html-markers#maps_advanced_markers_html-javascript

Regards,

Vishal

**Comment by valentasm1** [comment] 2022-11-12 09:29
Sorry but i am out of time. Only minor changes fixes.

**Comment by vishalsmart** [comment] 2022-11-12 09:29
I am trying to implement, if I will be success, shall I create PR?

**Comment by valentasm1** [comment] 2022-11-12 09:31
awesome. Any method which suits you. Here some similar issues
https://github.com/rungwiroon/BlazorGoogleMaps/issues/83
https://github.com/rungwiroon/BlazorGoogleMaps/issues/62

**Comment by vishalsmart** [comment] 2022-11-12 10:07
Thanks, I have success for implementing AdvancedMarkerView but need beta version of google map. Will explore more possibilities and will create check-in once all well tested.

**Comment by alelom** [comment] 2023-01-31 22:06
@vishalsmart any progress on this?

**Comment by vishaljani23** [comment] 2023-03-19 08:40
@alelom  @valentasm1  AdvancedMarkerView is still in Beta. Instead I have used RichMarker to achieve HTML markers. If @valentasm1 agrees, I can bit optimize my implementation and create PR to merge including richmarker https://github.com/googlearchive/js-rich-marker

**Comment by valentasm1** [comment] 2023-03-19 08:47
I am in progress migrating from json.net to system.text.json. Need some testing and adding some atributes. Most of work is done. I will finish next sunday. After that you could make PR :).  I will put reminder and will write here update.

**Comment by valentasm1** [comment] 2023-03-26 10:11
Everything looks working on migration to system.text.json, just need some testing and will release next week
https://github.com/rungwiroon/BlazorGoogleMaps/tree/system.text.json_migration

**Comment by vishalsmart** [comment] 2023-04-03 05:45
I tested and looks improved performance. I'm going to create PR for RichMarker in day or two.

**Comment by valentasm1** [comment] 2023-04-03 05:46
Awesome :).

**Comment by dkosinskyi** [comment] 2023-06-30 12:58
@valentasm1 what about PR? :)

**Comment by valentasm1** [comment] 2023-06-30 12:59
I never promised PR. I think you refering @vishalsmart

**Comment by coeur85** [comment] 2023-09-18 02:29
@valentasm1 , can you push it as a draft at least?

**Comment by valentasm1** [comment] 2023-09-18 04:53
I never promised PR. I think you refering @vishalsmart he said he will be ready in 2d (April 2023 :) )

**Comment by coeur85** [comment] 2023-09-18 07:43
> I never promised PR. I think you refering @vishalsmart he said he will be ready in 2d (April 2023 :) )

yes i'm tagging him

**Comment by dkosinskyi** [comment] 2023-09-18 11:14
@vishalsmart how are you? what about PR?)

**Comment by valentasm1** [comment] 2023-09-18 11:53
I like this part from article
_Advanced Markers can load up to 66% faster than our traditional markers, and provide faster panning and zooming._
https://cloud.google.com/blog/products/maps-platform/announcing-highly-customizable-higher-performance-markers

Just did quick draft. Doesnt look that it could be very complicated to implement from here.
https://github.com/rungwiroon/BlazorGoogleMaps/releases/tag/3.2.0

**Comment by coeur85** [comment] 2023-09-18 14:18
I managed to add this part, and so far it looks like a standard marker, I was working on adding the content parameter to the advanced maker, and this is where things got missy

**Comment by valentasm1** [comment] 2023-09-18 14:20
There is huge chance that you need to write exception in js file. There are already couple exception to some actions.

**Comment by valentasm1** [comment] 2023-09-18 14:26
Sorry but if i need to guide you is such cases i could implement it faster. I dont have much free time.
@Nickztar have you any thoughts about AdvancedMarkerView

**Comment by Nickztar** [comment] 2023-09-18 14:32
@coeur85 Would recommend going to the google docs, the error also says that the problem is that `content` is not a Node. Node is a HTMLElement (like a div or w/e). 

https://developers.google.com/maps/documentation/javascript/reference/advanced-markers#AdvancedMarkerElementOptions.content

Not sure how its currently handled in our library but we would have to send a reference to a htmlElement or do something about that. Might have a look tomorrow to see if I can help figure it out.

**Comment by Nickztar** [comment] 2023-09-18 14:35
Maybe you could allow the user to pass a `ElementReference` for content. That should be a Node when recieved by JS.

https://blazor-university.com/javascript-interop/calling-javascript-from-dotnet/passing-html-element-references/

**Comment by Nickztar** [comment] 2023-09-18 14:41
Well from what I can see you are just passing the string ´await CreateDiv(innerHTML)´? We would have to have something that overrides the call to `CreateAdvancedMarker` and calls that method (which sounds like a bad idea). You should probably just change Content to be a `ElementReference` and have the user call their own CreateDiv method which returns a `ElementRefence`.

**Comment by valentasm1** [comment] 2023-09-18 14:49
Wrong thinking. Content must by node since all params is serialized before passing to google maps passing reference is impossible.
https://developers.google.com/maps/documentation/javascript/reference/advanced-markers#AdvancedMarkerElementOptions.content

Need some workaround like here
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/wwwroot/js/objectManager.js#L603

**Comment by coeur85** [comment] 2023-09-21 08:28
sure you don't need my help

**Comment by valentasm1** [comment] 2023-10-25 05:41
Tomorrow never comes :).
I brute force and added just string property. Then do check in js.
@Nickztar  I tried to play ElementReference but unable to make it work. Even tho, if it could work then need to create separate ElementReference since gmaps dont duplicate it you pass same node.
https://github.com/rungwiroon/BlazorGoogleMaps/releases/tag/3.2.1
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/AdvancedMarkerViewPage.razor
Guy need opinion if it work. Maybe it super duper slow.

**Comment by Nickztar** [comment] 2023-10-25 06:53
Oh I have completely forgotten about it. This solution looks fine, maybe i'll get some more time soon and can try to do the elementReference. The "non-duplication" thing sounds like a feature to me, could save us from having to update the marker if it works as I think.

I guess a good solution might be to make Content a OneOf<string, ElementReference> but this should be fine until (if?) we figure it out 👍🏼

**Comment by valentasm1** [comment] 2023-10-29 18:42
For sure what is missing [PinElement](https://developers.google.com/maps/documentation/javascript/reference/advanced-markers#PinElement) . It could be again issues since it is HTMLElement. In other hand it dont have much properties and dont have much use case. IMO this view is most usefull for html content markers.

**Comment by valentasm1** [comment] 2024-04-04 14:59
As of February 21st, 2024 (v3.56), google.maps.Marker is deprecated. We encourage you to transition to the new google.maps.marker.AdvancedMarkerElement class. Advanced markers provide substantial improvements over the legacy google.maps.Marker class. The minimum version of the Maps JavaScript API with google.maps.marker.AdvancedMarkerElement is 3.53.2. At this time, google.maps.Marker is not scheduled to be discontinued.

https://developers.google.com/maps/documentation/javascript/markers
I will add this info to this library too and then close this issue.

**Comment by valentasm1** [comment] 2024-04-22 08:10
I dont think i need to add this to library since same info appears to browser console.

**Closed by valentasm1** 2024-04-22 08:10 UTC

**Comment by EGInsider** [comment] 2024-06-10 06:12
@valentasm1  Is there a AdvancedMarkerElement implementation available now??

**Comment by valentasm1** [comment] 2024-06-10 06:21
There is. It just use old naming AdvancedMarkerView. Google just renamed it to AdvancedMarkerElement 
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/AdvancedMarkerViewPage.razor

https://github.com/rungwiroon/BlazorGoogleMaps/issues/327
