### ISSUE TITLE
Orphaned DOM Nodes

### ISSUE THREAD

**Issue by FlySpray316** [rungwiroon/BlazorGoogleMaps#45] opened 2020-06-19 05:03 UTC
Appears that the Dispose method is not releasing all the objects from a javascript array.  This is causing the DOM Node Count  to increase indefinitely.  If the user visits a page that makes use of a map with markers/circles/polygons etc all those objects are never cleared from array when navigating away or calling Dispose().  Each time a user visits the page the DOM Node count increases.  

I made a quick hack which clears the array on dispose and solves the problem, but my js skills are not  good.   probably best if you can solve this one properly.

objectManager.js -> 

    dispose: function () {
        delete window._blazorGoogleMapsObjects;
    },

call this when user navigates away from the page and/or no longer needs any of the objects.

**Comment by valentasm1** [comment] 2020-06-19 06:51
Honsly i had this thought. Will check closer today

**Comment by valentasm1** [comment] 2020-06-19 07:36
Objects are released from memory cache, but like you said not from JavaScript. 
How you come with this conclusions?  I mean i would like to monitor and to reproduce by myself.

**Comment by FlySpray316** [comment] 2020-06-24 14:43
Hi,

Its possible i am not correct.  So glad if u can help me confirm. My JS skills are not great.  My webapp makes heavy use of markers and various shapes.  I use chrome dev tools to monitor the DOM node count and mem.

Step 1.  Start at the home page and click reload to make sure you are starting with a fresh DOM. which is very light.. about 800 nodes.

Step 2.  Navigate to the map and open lots of markers, shapes etc... about 2,500 nodes.

Step 3.  Navigate back to the home page and then trigger garbage collector using dev tools...  about 3,200 nodes.  Expected result would be 800 nodes (same as fresh home page)

Hope this helps.  Maybe you can reproduce the result??  Tomorrow I'll send you some screenshots.

Thanks,
Ron.

________________________________

**Comment by valentasm1** [comment] 2020-06-24 14:54
It is not that it is impossible for me, i just dont want to waste time where someone already had done everything and know where to click and see bug. 
I will wait for screenshots. Screenshots are always great :).

**Comment by FlySpray316** [comment] 2020-06-25 02:40
The attached screen shots are a series of actions...

home page 1.png 
Fresh DOM starting at home page.  Node count about 800

map page 2.png
Navigate to the map page whihc has heavy usage of your google map component.  Node count about 3200

home page 3 before garbage collector.png  as the file suggests, this is navigating away from map page back to the home page where we would expect a node count of about 800 again.  but remains on about 3200.

home page 4 after gabage collector.png.  clicking the garbage collector button in Chrome Dev Tools to trigger garbage collection, would expect the node count to return to 800.  but instead remains high.

home page 4 after garbage collector - with JS Hack - I'e included one extra screen shot, following the same steps as aboive, but with my JS hack to delte the object array on Dispose() of Map Page.  can see the node count returns to 850 (a little higher than before, but I can live).

![home page 4 after garbage collector](https://user-images.githubusercontent.com/58720496/85647098-48429f80-b6d0-11ea-9f5b-17822e368f5f.png)
![map page 2](https://user-images.githubusercontent.com/58720496/85647104-4a0c6300-b6d0-11ea-95c1-ca2c1f063ffe.png)
![home page 4 after garbage collector - with JS Hack](https://user-images.githubusercontent.com/58720496/85647105-4aa4f980-b6d0-11ea-80c4-5aa517046dab.png)
![home page 1](https://user-images.githubusercontent.com/58720496/85647107-4aa4f980-b6d0-11ea-985e-6d0e8f2e2fef.png)
![home page 3 before garbage collector](https://user-images.githubusercontent.com/58720496/85647109-4b3d9000-b6d0-11ea-865e-ebd73838725e.png)

**Comment by valentasm1** [comment] 2020-06-25 11:41
Big thumb up for description. Also bug is very good catch. I would give you medal if i could :). Great work.
Back to topic. It  is a bit complicated to remove. Just to clear all array it is a bit risky and could break a lot of people apps. So here is my suggestion. Map dispose is always called as expected. So when it is called then iterate through all array items and check if item have property map and map guid is same as disposed map. If true then remove. Problem that it finds only elements. Events isnt catched since they are promises.
I found some way but need more testing.
In a while you could inherit map component and on dispose call js function similar like this with map guid.

```
disposeMapElements(mapGuid) {
        var keysToRemove = [];
       
        for (var key in _blazorGoogleMapsObjects) {
            if (_blazorGoogleMapsObjects.hasOwnProperty(key)) {
                var element = _blazorGoogleMapsObjects[key];
                if (element.hasOwnProperty("map")
                    && element.hasOwnProperty("guidString")
                    && element.map.guidString === mapGuid) {
                    keysToRemove.push(element.guidString);
                }
            }
        }

        for (var keyToRemove in keysToRemove) {
            if (keysToRemove.hasOwnProperty(keyToRemove)) {
                var elementToRemove = keysToRemove[keyToRemove];
                delete window._blazorGoogleMapsObjects[elementToRemove];
            }
        }
    },

```

**Comment by valentasm1** [comment] 2020-06-25 11:41
I will try to test and release in week period.

**Comment by FlySpray316** [comment] 2020-06-26 01:13
Happy to help mate, and greatly appreciate you taking the time to look into this for me 🙂🙂


________________________________

**Comment by valentasm1** [comment] 2020-06-29 21:06
You said code bellow solves your problem. So does it solve on app or while testing and clicking garbage collector button?

```
dispose: function () {
    delete window._blazorGoogleMapsObjects;
},

```

**Comment by FlySpray316** [comment] 2020-06-30 01:15
It solves in the app.  But you have to wait for garbage collector to fire.

________________________________

**Comment by valentasm1** [comment] 2020-06-30 07:00
Hope will not ruin anything big :).
So removed part where promises(events) was added to array and part where elements is removed by they dependency of map. Code bellow.
Like you said you have to waith for garbage collector to fire. I have sense that there is better way to remove them faster.
Please check if all you functionality works as expected with package 0.6.6. Finger crossed.
https://www.nuget.org/packages/BlazorGoogleMaps/0.6.6


```
disposeMapElements(mapGuid) {
	var keysToRemove = [];
   
	for (var key in _blazorGoogleMapsObjects) {
		if (_blazorGoogleMapsObjects.hasOwnProperty(key)) {
			var element = _blazorGoogleMapsObjects[key];
			if (element.hasOwnProperty("map")
				&& element.hasOwnProperty("guidString")
				&& element.map.guidString === mapGuid) {
				keysToRemove.push(element.guidString);
			}
		}
	}

	for (var keyToRemove in keysToRemove) {
		if (keysToRemove.hasOwnProperty(keyToRemove)) {
			var elementToRemove = keysToRemove[keyToRemove];
			delete window._blazorGoogleMapsObjects[elementToRemove];
		}
	}
},

```

**Comment by valentasm1** [comment] 2020-07-03 19:13
Have you tried @FlySpray316 
Could you  confirm that all good and i  could close?

**Comment by FlySpray316** [comment] 2020-07-05 05:29
Sorry mate, just got your message.  I'll test on Tuesday and send results through.  Thanks again for your diligent help.  Greatly appreciated. :-)
________________________________

**Comment by FlySpray316** [comment] 2020-07-07 05:39
I've tested the 0.6.6 release... unfortunately the DOM Node count still seems to be increasing.  :-(

Just to confirm, on dispose of the page, I'm calling Map.Dispose(); am I meant to be calling anything/something else to dispose??  if yes, let me know; I can re-run the test.

screenshots attached...

Home page with Fresh DOM Node Count...
![1 Home Page Fresh DOM Node Count](https://user-images.githubusercontent.com/58720496/86719649-d87ccf00-c056-11ea-871b-edfa73e73cad.png)

Map Page with high DOM Node Count...
![2 Map Page High DOM Node Count](https://user-images.githubusercontent.com/58720496/86719655-da469280-c056-11ea-8fd2-4f2962be139a.png)

Home page with Hich DOM Node count BEFORE calling Garbage Collector...
![3 Home Page High DOM Node Count Before GC](https://user-images.githubusercontent.com/58720496/86719660-dadf2900-c056-11ea-9ff1-3bfa1e18473e.png)

Home page with High DOM Node count AFTER calling Garbage Collector... 
![4 Home Page High DOM Node Count After GC](https://user-images.githubusercontent.com/58720496/86719661-db77bf80-c056-11ea-9a96-196b7b4da643.png)

While the node count does drop, it seems there are still references that are not getting released.  If i was better with JS i would dive in and have a look, but I'd probably make it worse!! haha :)

This screenshot is me navigating to the map page and back to the home page several times, calling the Garbage Collector after each time.  
![5 Navigating to and from map page calling GC each time](https://user-images.githubusercontent.com/58720496/86719665-db77bf80-c056-11ea-8b70-4b9fa6558b33.png)

**Comment by valentasm1** [comment] 2020-07-07 06:16
Could you check number of element before and after with Object.keys(_blazorGoogleMapsObjects).length
Also after check what kind elements left in array _blazorGoogleMapsObjects . I assume removing it form array dont make dom node dissapear from stack. Aslo could you try to redirect from other page with refresh. As much as i read this is most reliable way to clear dom nodes.
Let my know your test results

**Comment by valentasm1** [comment] 2020-07-11 19:56
@FlySpray316 did you make a new finding? Have you tried my suggestions?

**Comment by FlySpray316** [comment] 2020-07-13 03:18
Sorry i have not tired your suggestion yet, I've got to finish some other tasks first.  
But in 3 weeks I can dedicate a full week to solving this.  Will send you a note when I start work on it.

**Comment by valentasm1** [comment] 2020-07-13 08:25
No rush. You are only one (i assume) which have such issue.

**Comment by valentasm1** [comment] 2020-09-19 19:07
I will close this issue in couple weeks if i wont get any response.

**Closed** 2020-10-09 10:06 UTC
